In [2]:
import sys
from pathlib import Path

# Force notebook to recognize project root
import os
ROOT = Path(os.getcwd()).resolve().parents[0] # one level up from tests/
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

import pandas as pd
from src.inference_pipeline.inference import predict

# Load a few rows of already preprocessed data
sample_path = ROOT / "data/processed/cleaning_eval.csv"
df = pd.read_csv(sample_path).sample(5, random_state=42).reset_index(drop=True)

print("Input sample:")
display(df.head())

# Run inference
preds_df = predict(df)
print("✅ Predictions returned")
display(preds_df[["predicted_income"]].head())

Input sample:

,age,ever_married,TIPOHO,reg_living,PAGOVI,studies,income,number_living,TRABAJAACT,type_contract,METROSRESID,INGREHOG_INTER,INGREHOG,INGRESOSPAR,number_children
0,37,5,1,4,2,8,878.32,1,1,2.0,4.0000,2,600.0,NaN,0
1,37,1,3,6,0,6,566.58,2,1,1.0,2.0000,3,1200.0,3.0,0
2,41,1,4,2,2,6,1468.72,3,1,1.0,1.6667,5,2100.0,4.0,1
3,44,4,2,2,1,7,1376.32,3,1,3.0,3.0000,4,1800.0,NaN,2
4,39,2,4,2,1,3,5187.30,3,1,3.0,2.0000,8,40000.0,6.0,1

✅ Dropped 0 duplicate rows (excluding date/year).
✅ Predictions returned

   predicted_income
0       1324.283081
1       1278.294312
2       1312.406250
3       1239.888184
4        742.215149